name: Get Scroll Mixin Api
port: 3000
host: 0.0.0.0
database: database.json

# auth:
#   jwtSecret: cwsMXDtuP447WZQ63nM4dWZ3RppyMl
#   jwtExpire: 3600
#   unauthorizedStatusCode: 401
#   urlSkip:
#     - /users:
#        method: post
#      - /products/{*}:
#        method: get
